[package]
name = "siren_engine"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
tract-onnx = "0.21"
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2"
tokenizers = { version = "0.19.1", default-features = false, features = ["unstable_wasm"] }
